### ISSUE TITLE
Navegação com problemas fora do Chrome

### ISSUE THREAD

**Issue by julianasakai** [analytics-ufcg/ta-na-mesa#131]
A setinha de voltar não está funcionando no Safari e no Firefox.

**Comment by luizaugustomm** [comment]
Não consegui reproduzir no Safari, Juliana. Tem como você dizer exatamente qual o passo a passo que você fez e não funcionou?

**Comment by julianasakai** [comment]
Em Gravataí, linha do tempo, cliquei na licitação 52.
Dentro de licitação 52 cliquei na setinha e ela não voltou. 
No Chrome, ela volta. 
Em outra licitação(115) mesmo no Safari a setinha de voltar está funcionando.
